### ISSUE TITLE
behavoir sszSelectInput different by multiple = TRUE

### ISSUE THREAD

**Issue by christophbaur** [StatistikStadtZuerich/zuericssstyle#11]
## Issue

The "sszSelectInput" has a curious behavior when using multiple selection. 
When Multiple = FALSE it looks as expected, when Multiple = TRUE it partially goes to the Shiny default. See here:
![image](https://user-images.githubusercontent.com/69149103/231738709-4e3fd385-335d-4eb0-8ffe-7061040ceaca.png)

## expected behavoir
Same Style, regardless of using `multiple = TRUE` or `multiple =FALSE `

## example

```R
#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
library(shiny)
library(zuericssstyle)

# Define UI for application that draws a histogram
ui <- fluidPage(
  #CSS-Style laden
  if(file.exists("sszThemeShiny.css")){
    includeCSS("sszThemeShiny.css")
  }else{
    get_shiny_css()
    includeCSS("sszThemeShiny.css")
    },
  sszSelectInput(
    inputId = "single",
    label = "single select:",
    choices = c("Option 1", "Option 2", "Option 3"),
    multiple = FALSE
    
  ),
  
  sszSelectInput(
    inputId = "multi",
    label = "multi select:",
    choices = c("Option 1", "Option 2", "Option 3"),
    multiple = TRUE
    
  )
    
)
# Define server logic required to draw a histogram
server <- function(input, output) {
    
}
# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by shaenzi** [comment]
we'll have a look, TBD whether we implement only the first of these levels or more

1. make sure we do not lose the styling of the drop-down with `multiple = TRUE`
2. style the selections according to the DESI, as a [chip](https://designsystem.stadt-zuerich.ch/current/?path=/story/components-chip--input) but without the 'x' for unselection
3. implement the "x" for unselection (not sure whether this is possible with this shiny widget)

**Comment by alfell** [comment]
Hi @christophbaur! Updated sszSelectInput in zuericssstyle (version: 0.0.1.0002) so that styling of multiple = TRUE is the same as multiple = FALSE. Note that selectize input created from sszSelectInput is based on selectizeInput and allows deletion of the selected option even in a single event input, which will return an empty string as its value (https://shiny.posit.co/r/reference/shiny/0.11/selectinput).
