### ISSUE TITLE
sszSliderInput

### ISSUE THREAD

**Issue by christophbaur** [StatistikStadtZuerich/zuericssstyle#12]
Include sliderInput() also in zuericssstyle.
At the moment its missing.

**Comment by alinelaura** [comment]
The widget sliderInput() has been added to zuericssstyle (package version 0.0.1.0). The function called 'sszSliderInput()' wraps around shiny's sliderInput. Currently there is no DESI component for the styling and functionality of the sliderInput. A ticket to create a DESI component for this widget has been made and it will be adapted in the zuericsssytle package when completed. Therefore the styling for the sliderInput might vary slightly at a later point in time (2023-07-12).
